
// 商品、耗材字段定义
const MODEL_SPECIFICATION = 'SXX000008' // 型号规格 \ 规格
const UNIT_OF_MEASUREMENT = 'SXX000048' // 计量单位
const CHINESE_MODEL_SPECIFICATION = 'SXX000049' // 中药规格
export const WARES_PACKAGE_CODE = [MODEL_SPECIFICATION, UNIT_OF_MEASUREMENT] // 商品、耗材包装规格
export const CHINESE_MEDICINE_PACKAGE_CODE = [CHINESE_MODEL_SPECIFICATION, UNIT_OF_MEASUREMENT] // 中药包装规格
export const PACKAGE_MUSTER = { // 物资单位集合（中药、耗材、商品）
  WARES_PACKAGE_CODE,
  CHINESE_MEDICINE_PACKAGE_CODE
}
