import { GENERATE_UUID as U } from '@/bi/util/reportsetuuid'

export const tableData = [
  {
    id: U(),
    param: 'value/v-model',
    description: '绑定值',
    type: 'Array, String, Object, Number',
    required: true,
    default: '',
  },
  {
    id: U(),
    param: 'props',
    description: 'el-select或者el-cascader或者el-tree的属性，当现有的属性不够用时，才在此属性中添加',
    type: 'object',
    required: false,
  },
  {
    id: U(),
    param: 'isOrg',
    description: '控制查询条件，为true表示查询条件为登录人当前选择的登录机构，为false表示查询条件为当前登录人所属的集团',
    type: 'Boolean',
    required: false,
    default: 'true',
  },
  {
    id: U(),
    param: 'useOrg',
    description: '控制查询结果，为true表示查询结果为机构科室，为false表示查询结果为集团科室',
    type: 'Boolean',
    required: false,
    default: 'true',
  },
  {
    id: U(),
    param: 'type',
    description: 'cascader select tree 其中cascader 是默认值',
    type: 'String',
    required: false,
    default: 'cascader',
  },
  {
    id: U(),
    param: 'multiple',
    description: '是否多选',
    type: 'Boolean',
    required: false,
    default: 'false',
  },
  {
    id: U(),
    param: 'params',
    description: '附加查询参数',
    type: 'Object',
    required: false,
    default: '{}',
  },
  {
    id: U(),
    param: 'cascaderProps',
    description: '是否多选',
    type: 'Object',
    required: false,
    default: '{checkStrictly: true,}',
  },
  {
    id: U(),
    param: 'fields',
    description: '下拉内容一行数据中的带有的key',
    type: 'Array, String',
    required: false,
    default: '[ \'id\',\'orgSubjectCode\',\'orgSubjectName\',]',
  },
  {
    id: U(),
    param: 'disabled',
    description: '是否禁用',
    type: 'Boolean',
    required: false,
    default: 'false',
  },
  {
    id: U(),
    param: 'isManage',
    description: '是否是管理员使用，默认为false，为true时，调用的接口为对内的接口',
    type: 'Boolean',
    required: false,
    default: 'false',
  },
  {
    id: U(),
    param: 'placeholder',
    description: '提示文案',
    type: 'String',
    required: false,
    default: '',
  },
  {
    id: U(),
    param: 'afterNotMatch',
    description: '如果没有查询到结果处理逻辑  // \'1\': 抛出有未匹配数据的事件  // \'2\': 直接清除未匹配的数据',
    type: 'String',
    required: false,
    default: '1',
  },
  {
    id: U(),
    param: 'useInput',
    description: '此属性设为true之后，可以使该选择器变为输入框，鸡肋用法',
    type: 'Boolean',
    required: false,
    default: 'false',
  },
]
export const paramsData = [
  {
    id: U(),
    param: 'orgId',
    description: 'orgIdList条件的字符串形式',
    type: 'string',
  },
  {
    id: U(),
    param: 'status',
    description: '可选值Y/N，默认为Y',
    type: 'string',
    default: 'Y',
  },
]
